### ISSUE TITLE
Error: when running in server mode, the 'prefix' and 'info' config parameters are required

### ISSUE THREAD

**Issue by snackyoung** [interledgerjs/ilp-lightning-demo#2]
when i run 'node run-connector.js', errors happened:
Getting configuration details from lnds
Running connector using lightning plugins...
2018-01-21T11:56:13.514Z connector:ledgers info adding ledger g.bitcoin.lightning.
Error: when running in server mode, the 'prefix' and 'info' config parameters are required
    at new PluginPaymentChannel (/home/snack/interlightning/ilp-lightning-demo/node_modules/ilp-plugin-payment-channel-framework/src/lib/plugin.js:136:13)
    at Ledgers.add (/home/snack/interlightning/ilp-lightning-demo/node_modules/ilp-connector/src/lib/ledgers.js:95:20)
    at Ledgers.addFromCredentialsConfig (/home/snack/interlightning/ilp-lightning-demo/node_modules/ilp-connector/src/lib/ledgers.js:44:12)
    at createApp (/home/snack/interlightning/ilp-lightning-demo/node_modules/ilp-connector/src/app.js:100:13)
    at Object.<anonymous> (/home/snack/interlightning/ilp-lightning-demo/node_modules/ilp-connector/src/index.js:4:19)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/snack/interlightning/ilp-lightning-demo/node_modules/connector-rpc/index.js:8:19)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)

**Comment by michielbdejong** [comment]
Thanks for reporting! I'll have a look.

**Comment by hugo-tardiou** [comment]
Got this error as well, any updates? thanks

**Comment by michielbdejong** [comment]
we're now working on a new lightning integration, will post here when it's ready!

**Comment by michielbdejong** [comment]
You can now try out the new BTP+LND client plugin against the Interledger testnet: https://github.com/interledgerjs/ilp-plugin-lnd-asym-client

**Comment by snackyoung** [comment]
@michielbdejong You mean combine this demo with the ilp-plugin-lnd-asym-client? Could you explain more specificlly? Thx!!
